const themes = {
    'default': "an-old-hope.css",
    'A 11 Y Dark': 'a11y-dark.css',
    'Atom One Dark': 'atom-one-dark.css',
    'Atom One Dark Reasonable': 'atom-one-dark-reasonable.css',
    'Atelier Estuary': "atelier-estuary-dark.css",
    'Ashes': 'ashes.min.css',
    "Black Metal": 'black-metal-immortal.min.css',
    "Bright":"bright.min.css",
    "Cupertino": "cupertino.min.css",
    'Color brewer': 'color-brewer.css',
    'Darcula': "darcula.css",
    'Dracula': 'dracula.css',
    'Dark Violet': "dark-violet.min.css",
    "Edge Dark": "edge-dark.css",
    "Edge Light": 'edge-light.css',
    "Espresso": 'espresso.min.css',
    "Hardcore":"hardcore.min.css",
    'Github': 'github.css',
    'Google Dark': 'google-dark.min.css',
    'Google Light': 'google-light.min.css',
    'Green Screen': 'green-screen.min.css',
    'GruvBox': 'gruvbox-dark-hard.min.css',
    'Harmonic 16': 'harmonic16-dark.min.css',
    'Helios': 'helios.min.css',
    'Icy Dark': 'icy-dark.min.css',
    'Ir black': 'ir-black-min.css',
    'Kimber': 'kimber.min.css',
    'London Tube': 'london-tube.min.css',
    'Marrakesh': 'marrakesh.min.css',
    'Material Palenight': 'material-palenight.min.css',
    'Mocha': 'mocha.min.css',
    'Monokai': 'monokai.min.css',
    'Nebula': 'nebula.min.css',
    
}

export default themes