const themes = {
    "A 11 Y Dark": "a11y-dark",
    "Ashes": "ashes.min",
    "Atelier Estuary": "atelier-estuary-dark",
    "Atom One Dark": "atom-one-dark",
    "Atom One Dark Reasonable": "atom-one-dark-reasonable",
    "Black Metal": "black-metal-immortal.min",
    "Bright": "bright.min",
    "Color brewer": "color-brewer",
    "Cupertino": "cupertino.min",
    "Darcula": "darcula.min",
    "Dark Violet": "dark-violet.min",
    "Dracula": "dracula.min",
    "Edge Dark": "edge-dark.min",
    "Edge Light": "edge-light.min",
    "Espresso": "espresso.min",
    "Github": "github",
    "Google Dark": "google-dark.min",
    "Google Light": "google-light.min",
    "Green Screen": "green-screen.min",
    "GruvBox": "gruvbox-dark-hard.min",
    "Hardcore": "hardcore.min",
    "Harmonic 16": "harmonic16-dark.min",
    "Helios": "helios.min",
    "Icy Dark": "icy-dark.min",
    "Ir black": "ir-black.min",
    "Kimber": "kimber.min",
    "London Tube": "london-tube.min",
    "Marrakesh": "marrakesh.min",
    "Material Palenight": "material-palenight.min",
    "Mocha": "mocha.min",
    "Monokai": "monokai.min",
    "Nebula": "nebula.min"
  }

export default themes