const themes = {
    'Default': "an-old-hope",
    'A 11 Y Dark': 'a11y-dark',
    'Atom One Dark': 'atom-one-dark',
    'Atom One Dark Reasonable': 'atom-one-dark-reasonable',
    'Atelier Estuary': "atelier-estuary-dark",
    'Ashes': 'ashes.min',
    "Black Metal": 'black-metal-immortal.min',
    "Bright":"bright.min",
    "Cupertino": "cupertino.min",
    'Color brewer': 'color-brewer',
    'Darcula': "darcula.min",
    'Dracula': 'dracula.min',
    'Dark Violet': "dark-violet.min",
    "Edge Dark": "edge-dark.min",
    "Edge Light": 'edge-light.min',
    "Espresso": 'espresso.min',
    "Hardcore":"hardcore.min",
    'Github': 'github',
    'Google Dark': 'google-dark.min',
    'Google Light': 'google-light.min',
    'Green Screen': 'green-screen.min',
    'GruvBox': 'gruvbox-dark-hard.min',
    'Harmonic 16': 'harmonic16-dark.min',
    'Helios': 'helios.min',
    'Icy Dark': 'icy-dark.min',
    'Ir black': 'ir-black.min',
    'Kimber': 'kimber.min',
    'London Tube': 'london-tube.min',
    'Marrakesh': 'marrakesh.min',
    'Material Palenight': 'material-palenight.min',
    'Mocha': 'mocha.min',
    'Monokai': 'monokai.min',
    'Nebula': 'nebula.min',
    
}

export default themes